# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/images/ingredient'
        aws1.storage:
            adapter: 'aws'
            options: 
                client: Aws\S3\S3Client
                bucket: '%env(AWS_BUCKET1_NAME)%'
        aws2.storage:
            adapter: 'aws'
            options: 
                client: Aws\S3\S3Client
                bucket: '%env(AWS_BUCKET2_NAME)%'
