fm_elfinder:
    assets_path: bundles/fmelfinder
    instances:
        default:
            locale: kernel.default_locale
      
            editor: ckeditor
            relative_path: true
            theme: smoothness
            connector:
                debug: false
                roots:
                    uploads:
                        
                        driver: LocalFileSystem
                        path: uploads/images
                        show_hidden: false
                        upload_allow: ['image/png','image/jpg','image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M