fm_elfinder:
    assets_path: web/assets
    instances:
        default:
            locale: kernel.default_locale
            editor: ckeditor
            relative_path: true
            theme: smoothness
            connector:
                debug: false
                roots:
                    uploads:
                        driver: Flysystem
                        url: '%env(AWS_BASE1_URL)%'
                        flysystem: 
                            type: aws_s3_v3
                            options: 
                                aws_s3_v3:
                                    key: '%env(AWS_KEY)%'
                                    secret: '%env(AWS_SECRET_KEY)%'
                                    region: eu-west-3
                                    bucket_name: '%env(AWS_BUCKET1_NAME)%'
                                    version: latest
                        show_hidden: false
                        upload_allow: ['image/png','image/jpg','image/jpeg','image/webp','image/gif']
                        upload_deny: ['all']
                        upload_max_size: 2M