vich_uploader:
    db_driver: orm
    metadata:
        type: attribute


    mappings:
        recipe_images:
           uri_prefix: /
           upload_destination: '%kernel.project_dir%/public'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        ingredient_images:
           uri_prefix: /
           upload_destination: '%kernel.project_dir%/public'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       