
vich_uploader:
    db_driver: orm
    storage: flysystem
    metadata:
        type: attribute

    mappings:
        recipe:
            uri_prefix: '%env(AWS_BASE2_URL)%'
            upload_destination: aws2.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        ingredient:
          
           uri_prefix:  '%env(AWS_BASE2_URL)%'
           upload_destination: aws2.storage
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer